#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
 

/*
 * 1000 ms = 24"
 * 2100 ms = 50"
 * 3300 ms = 72"
 */

// Move forward 
void moveForward(int time) {
  motor[leftMotor] = 127;
  motor[rightMotor] = 127;
  wait1Msec(time);
}

// Sharp right turn
void sharpRight(int time) {
  motor[leftMotor] = 63;
  motor[rightMotor] = -63;
  wait1Msec(time);
}

// Sharp left turn
void sharpLeft(int time) {
  motor[leftMotor] = -63;
  motor[rightMotor] = 63;
  wait1Msec(time);
}

task main() {
 
  // Section 1
  moveForward(1000);
  sharpRight(1250);
 // Section 2
  moveForward(1000);
  sharpRight(1250);
 // Section 3
  moveForward(1000);
  sharpLeft(1250);
 // Section 4
  moveForward(3300);
  sharpLeft(1250);
 // Section 5
  moveForward(2100);
  sharpLeft(1250);
 // Section 6
  moveForward(1000);
  sharpLeft(1250);
 // Section 7
  moveForward(1000);
  sharpRight(1250);
 // Section 8
  moveForward(1000);
  sharpRight(1250);
 // Section 9
  moveForward(1000);
  sharpLeft(1300);
 // Section 10
  moveForward(1666);

}
